FROM openjdk:21-slim-buster as user

WORKDIR /apps

COPY ./user-service .

RUN chmod 777 ./mvnw
RUN ./mvnw clean install

FROM openjdk:21-slim-buster as project

WORKDIR /apps

COPY --from=user /root/.m2 /root/.m2

COPY ./project-service .

RUN chmod 777 ./mvnw
RUN ./mvnw clean install

FROM openjdk:21-slim-buster as company

WORKDIR /apps

COPY --from=project /root/.m2 /root/.m2

COPY ./company-service .
RUN chmod 777 ./mvnw

RUN ./mvnw clean install

FROM openjdk:21-slim-buster as build

WORKDIR /photo-service

COPY --from=company /root/.m2 /root/.m2

COPY ./photo-service/.mvn .mvn
COPY ./photo-service/mvnw .
COPY ./photo-service/pom.xml .

RUN chmod 777 ./mvnw
RUN ./mvnw -B dependency:go-offline

COPY ./photo-service/src src

RUN ./mvnw -B package

FROM openjdk:21-slim-buster

COPY --from=build /photo-service/target/photo-service-0.0.1-SNAPSHOT.jar .

EXPOSE 8088

ENTRYPOINT ["java", "-jar","-Dspring.profiles.active=prod", "photo-service-0.0.1-SNAPSHOT.jar"]