version: "3"

services:
  #Eureka Server#
  eureka-server:
    build: ./eureka-server
    ports:
      - "8081:8081"
    networks:
      - service_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  #Project Service#
  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    networks:
      - service_network
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  #Project Service#
  amenities-service:
    build: ./amenities-service
    ports:
      - "8084:8084"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  company-service:
    build: ./company-service
    ports:
      - "6789:6789"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  developers-service:
    build:
      dockerfile: ./Dockerfile-developers
    ports:
      - "8086:8086"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  folders-service:
    build:
      dockerfile: ./Dockerfile-folders
    ports:
      - "8087:8087"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  photo-service:
    build:
      dockerfile: ./Dockerfile-photo
    ports:
      - "8088:8088"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - company-service
      - project-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  project-service:
    build:
      dockerfile: ./Dockerfile-project
    ports:
      - "8090:8090"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  saved-service:
    build:
      dockerfile: ./Dockerfile-saved
    ports:
      - "8091:8091"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  #API Gateway#
  api-gateway:
    build: ./api-gateway
    ports:
      - "8089:8089"
    networks:
      - service_network
    depends_on:
      - eureka-server

networks:
  service_network:
    driver: bridge
