FROM openjdk:21-slim-buster as user

WORKDIR /apps

COPY ./user-service .

RUN chmod 777 ./mvnw
# RUN ./mvnw -B dependency:go-offline

# RUN ./mvnw -B package
RUN ./mvnw clean install

FROM openjdk:21-slim-buster as build

WORKDIR /saved-service

COPY --from=user /root/.m2 /root/.m2

COPY ./saved-service/.mvn .mvn
COPY ./saved-service/mvnw .
COPY ./saved-service/pom.xml .

RUN chmod 777 ./mvnw
RUN ./mvnw -B dependency:go-offline

COPY ./saved-service/src src

RUN ./mvnw -B package

FROM openjdk:21-slim-buster

COPY --from=build /saved-service/target/saved-service-0.0.1-SNAPSHOT.jar .

EXPOSE 8091

ENTRYPOINT ["java", "-jar","-Dspring.profiles.active=prod", "saved-service-0.0.1-SNAPSHOT.jar"]